
export const MOCK_PATIENTS = [
    {
        id: 1,
        name: "Arjun Sharma",
        age: 34,
        condition: "Hypertension",
        status: "pending",
        date: "2026-03-06",
        avatar: "AS",
        phone: "+91-9876543210",
        email: "arjun@email.com",
        lastVisit: "2026-02-15",
    },
    {
        id: 2,
        name: "Priya Patel",
        age: 28,
        condition: "Diabetes Type 2",
        status: "approved",
        date: "2026-03-06",
        avatar: "PP",
        phone: "+91-9123456789",
        email: "priya@email.com",
        lastVisit: "2026-03-01",
    },
    {
        id: 3,
        name: "Rahul Verma",
        age: 45,
        condition: "Cardiac Checkup",
        status: "pending",
        date: "2026-03-07",
        avatar: "RV",
        phone: "+91-9988776655",
        email: "rahul@email.com",
        lastVisit: "2026-01-20",
    },
    {
        id: 4,
        name: "Meera Singh",
        age: 52,
        condition: "Arthritis",
        status: "approved",
        date: "2026-03-07",
        avatar: "MS",
        phone: "+91-9871234560",
        email: "meera@email.com",
        lastVisit: "2026-02-28",
    },
    {
        id: 5,
        name: "Karan Gupta",
        age: 19,
        condition: "Fever & Cold",
        status: "rejected",
        date: "2026-03-05",
        avatar: "KG",
        phone: "+91-9765432109",
        email: "karan@email.com",
        lastVisit: "2026-03-05",
    },
    {
        id: 6,
        name: "Sunita Rao",
        age: 61,
        condition: "Osteoporosis",
        status: "pending",
        date: "2026-03-08",
        avatar: "SR",
        phone: "+91-9654321098",
        email: "sunita@email.com",
        lastVisit: "2025-12-10",
    },
];

export const MOCK_REVIEWS = [
    {
        id: 1,
        patient: "Arjun Sharma",
        rating: 5,
        text: "Excellent doctor! Very thorough and explained everything clearly.",
        date: "2026-02-20",
        avatar: "AS",
    },
    {
        id: 2,
        patient: "Priya Patel",
        rating: 4,
        text: "Good consultation, wait time was a bit long but overall satisfied.",
        date: "2026-03-02",
        avatar: "PP",
    },
    {
        id: 3,
        patient: "Meera Singh",
        rating: 5,
        text: "Dr. is very knowledgeable and caring. Highly recommended!",
        date: "2026-03-01",
        avatar: "MS",
    },
    {
        id: 4,
        patient: "Rahul Verma",
        rating: 3,
        text: "Average experience. Could improve on follow-up care.",
        date: "2026-01-25",
        avatar: "RV",
    },
];

export const MOCK_BILLING = [
    {
        id: "INV-001",
        patient: "Priya Patel",
        date: "2026-03-01",
        service: "Consultation",
        amount: 500,
        status: "paid",
        pkg: "Basic",
    },
    {
        id: "INV-002",
        patient: "Meera Singh",
        date: "2026-03-02",
        service: "Follow-up + Labs",
        amount: 1200,
        status: "paid",
        pkg: "Standard",
    },
    {
        id: "INV-003",
        patient: "Arjun Sharma",
        date: "2026-03-05",
        service: "Checkup",
        amount: 800,
        status: "pending",
        pkg: "Basic",
    },
    {
        id: "INV-004",
        patient: "Rahul Verma",
        date: "2026-03-06",
        service: "Cardiac Panel",
        amount: 2500,
        status: "pending",
        pkg: "Premium",
    },
    {
        id: "INV-005",
        patient: "Sunita Rao",
        date: "2026-02-28",
        service: "Bone Density Scan",
        amount: 1800,
        status: "paid",
        pkg: "Standard",
    },
    {
        id: "INV-006",
        patient: "Karan Gupta",
        date: "2026-03-05",
        service: "Consultation",
        amount: 500,
        status: "overdue",
        pkg: "Basic",
    },
];

export const MOCK_COMMS = {
    2: {
        msgs: [
            {
                from: "patient",
                text: "Hello Doctor, I have been having high sugar levels.",
                time: "10:15 AM",
            },
            {
                from: "doctor",
                text: "Hello Priya, please share your recent sugar readings.",
                time: "10:18 AM",
            },
            {
                from: "patient",
                text: "Fasting was 180 and post meal was 260 yesterday.",
                time: "10:20 AM",
            },
            {
                from: "doctor",
                text: "That is elevated. Let's adjust your medication. Please come in on Thursday.",
                time: "10:22 AM",
            },
        ],
        calls: [
            { type: "voice", duration: "4:32", time: "Yesterday 2:15 PM" },
            { type: "video", duration: "12:08", time: "2026-03-01 10:00 AM" },
        ],
    },
    4: {
        msgs: [
            {
                from: "patient",
                text: "Doctor, my knee pain is getting worse.",
                time: "9:00 AM",
            },
            {
                from: "doctor",
                text: "I am sorry to hear that. Are you taking the prescribed anti-inflammatories?",
                time: "9:05 AM",
            },
        ],
        calls: [{ type: "voice", duration: "2:14", time: "2026-02-28 4:00 PM" }],
    },
};


export const PATIENT_TREND = [
    { month: "Sep", patients: 38, checkups: 30 },
    { month: "Oct", patients: 45, checkups: 38 },
    { month: "Nov", patients: 52, checkups: 44 },
    { month: "Dec", patients: 41, checkups: 35 },
    { month: "Jan", patients: 60, checkups: 50 },
    { month: "Feb", patients: 75, checkups: 62 },
    { month: "Mar", patients: 68, checkups: 58 },
];
export const CONDITION_DATA = [
    { name: "Hypertension", value: 28, color: "#16a34a" },
    { name: "Diabetes", value: 22, color: "#15803d" },
    { name: "Cardiac", value: 18, color: "#4ade80" },
    { name: "Arthritis", value: 16, color: "#86efac" },
    { name: "Other", value: 16, color: "#cbd5e1" },
];
export const WEEKLY_APT = [
    { day: "Mon", apt: 8, done: 7 },
    { day: "Tue", apt: 12, done: 11 },
    { day: "Wed", apt: 10, done: 9 },
    { day: "Thu", apt: 15, done: 14 },
    { day: "Fri", apt: 11, done: 10 },
    { day: "Sat", apt: 6, done: 6 },
];
export const RATING_TREND = [
    { month: "Sep", rating: 4.2 },
    { month: "Oct", rating: 4.4 },
    { month: "Nov", rating: 4.3 },
    { month: "Dec", rating: 4.6 },
    { month: "Jan", rating: 4.7 },
    { month: "Feb", rating: 4.8 },
    { month: "Mar", rating: 4.8 },
];
export const RADIAL_DATA = [
    { name: "Success Rate", value: 97, fill: "#16a34a" },
    { name: "Satisfaction", value: 92, fill: "#4ade80" },
    { name: "Revisit Rate", value: 78, fill: "#86efac" },
];
export const REVENUE_DATA = [
    { month: "Sep", revenue: 18000 },
    { month: "Oct", revenue: 22000 },
    { month: "Nov", revenue: 19500 },
    { month: "Dec", revenue: 25000 },
    { month: "Jan", revenue: 28000 },
    { month: "Feb", revenue: 31000 },
    { month: "Mar", revenue: 27500 },
];

export const INITIAL_SERVICE = {
    name: "",
    category: "",
    status: "incomplete",
    specialty: "",
    licenseNo: "",
    experience: "",
    phone: "",
    email: "",
    emergencyEmail: "",
    basePrice: "",
    about: "",
    profilePic: null,
    treatments: [],
    specialists: [],
    pricing: [],
    businessHours: [
        { day: "Monday", isOpen: true, time: "09:00 AM - 05:00 PM" },
        { day: "Tuesday", isOpen: true, time: "09:00 AM - 05:00 PM" },
        { day: "Wednesday", isOpen: true, time: "09:00 AM - 05:00 PM" },
        { day: "Thursday", isOpen: true, time: "09:00 AM - 05:00 PM" },
        { day: "Friday", isOpen: true, time: "09:00 AM - 05:00 PM" },
        { day: "Saturday", isOpen: true, time: "10:00 AM - 02:00 PM" },
        { day: "Sunday", isOpen: false, time: "" },
    ],
    rating: "-",
    reviewsCount: "-",
    patientsTreated: "-",
    successRate: "-",
};
